public enum GunUpgradeType
{
    Damage = 0,
    FireRate = 1,
    BulletCount = 2,
    MultiBulletAngle = 3,
    BulletLifeTime = 4,
    Pierce = 5,
    Explode = 6,
    Split = 7,
    Ricochet = 8,
    Wave = 9,
    SizeMultiplier = 10,
    HeatSeeking = 11,
    Slowing = 12,
    BulletSize = 13,
    Element = 14,
    CriticalChance = 15,
    CriticalMultiplier = 16,
    LifeSteal = 17,
    ArmorPierce = 18,
    AcidRounds = 19,
    MultiDirectionalShot = 21,
    KnockBack = 22,
    ExplosionRadius = 23,
    AuraBullets = 24
}